version: "3.6"

services:
  main:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    command: bash -x /run.sh
    volumes:
      - ./.ssh:/root/.ssh
      - ./run.sh:/run.sh
    environment:
      GIT_USERNAME: "actions-user"
      GIT_EMAIL: "3856350+guitarrapc@users.noreply.github.com"
      BUCKET: "guitarrapc/scoop-bucket"
