name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "scoop=${{ runner.workspace }}\project\scoop" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "scoop_home=${{ runner.workspace }}\project\scoop" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "scoop_helpers=${{ runner.workspace }}\project\helpers" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "lessmsi=${{ runner.workspace }}\project\lessmsi\lessmsi.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "innounp=${{ runner.workspace }}\project\innounp\innounp.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - run: |
          echo "$env:GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
          echo "$env:JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
      - run: |
          echo "$env:RUNNER_CONTEXT"
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
      - run: "ls env:"
      - run: pwd
      - run: if(!(Test-Path "$env:SCOOP")) { git clone -q --depth=1 "https://github.com/lukesampson/scoop" "$env:SCOOP" }
      - run: . "$env:SCOOP_HOME\test\bin\init.ps1"
      - run: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "${{ runner.workspace }}"
