name: update bucket

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  excavate:
    permissions:
      contents: write
    runs-on: windows-2025
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Excavator
        uses: ScoopInstaller/GithubActions@e174c3bef2aeec16a40f2f075cafa167733f0a3e # main (Nov 25, 2025)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
